# Generated by Django 6.1 on 2026-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('decision', models.CharField(max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
